config/routes.rb
KwEcoMeencontra::Application.routes.draw do

  resources :contacts do 
    member do
        get 'new_id'
    end
  end
  get "privacy_policy/index"

  get "terms_of_user/index"

  get "howitwork/index"
  resources :providers

  get "home/index"

  resources :search do
    collection do
        post 'results'
    end
  end
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  namespace(:admin){
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #attr_accessible :name, :e_mail, :message, :provider_id
  belongs_to :provider
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  #attr_accessible :name, :last_name, :address, :city, :state, :zip_code, :number, :phone, :mobile, :e_mail, :category, :business, :area_of_​​expertise, :business_phone, :availability, :performance_field
  has_many :contacts 
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout "home"
  def index
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  layout "internal"
  def index
    @providers = Provider.all
  end

  def show
    @provider = Provider.find(params[:id])
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new(params[:provider])
    if @provider.save
      redirect_to @provider, :notice => "Successfully created provider."
    else
      render :action => 'new'
    end
  end

  def edit
    @provider = Provider.find(params[:id])
  end

  def update
    @provider = Provider.find(params[:id])
    if @provider.update_attributes(params[:provider])
      redirect_to @provider, :notice  => "Successfully updated provider."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy
    redirect_to providers_url, :notice => "Successfully destroyed provider."
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 layout "internal"
  def index
  
  end
  
  def new
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    #@Estados = Reseller.all(:conditions => "active =  true", :group => "state", :order => "state ASC")
    
  end
  
  def results
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    
    #Parameters: {"search"=>{"atuacao"=>"teste2", "categoria"=>"sp", "disponibilidade"=>"teste2"}, "utf8"=>"✓", "y"=>"26", "x"=>"62", "cidade"=>""}
    
    @Resultados = Provider.all(:conditions => ['area_of_​​expertise = ? AND state = ? AND availability = ?', params[:search][:atuacao],params[:search][:estado], params[:search][:disponibilidade]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if !@user.update_attributes(params[:user])
      @user.errors
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/howitwork_helper.rb
module HowitworkHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/privacy_policy_helper.rb
module PrivacyPolicyHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/serach_helper.rb
module SerachHelper
end

app/helpers/terms_of_user_helper.rb
module TermsOfUserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/providers/_form.html.erb
<%= form_for @provider ,:html => {:id => "formID"} do |f| %>
  <%= f.error_messages %>
  
    <%= f.label :name , "NOME"  %><br />
    <%= f.text_field :name , :class =>"a_content1_input validate[required]"  %>
    
  
    <%= f.label :last_name, "SOBRENOME"  %><br />
    <%= f.text_field  :last_name , :class =>"a_content1_input validate[required]" %>
    
  
    <%= f.label :address , "ENDEREÇO"  %><br />
    <%= f.text_field :address , :class =>"a_content1_input validate[required]"  %>
    
  
    <%= f.label :city, "CIDADE"  %><br />
    <%= f.text_field :city , :class =>"a_content1_input validate[required]"  %>
    
    <%= f.label :state, "ESTADO:", :class =>"uf dk validate[required]"%> 
    <%= f.select :state, ([["AC", "AC"], ["AL","AL"], ["AP", "AP"], ["AM", "AM"], ["BA", "BA"], ["CE", "CE"], ["DF", "DF"], ["ES", "ES"], ["GO", "GO"], ["MA", "MA"], ["MT", "MT"], ["MS", "MS"], ["MG", "MG"], ["PA", "PA"], ["PB", "PB"], ["PR", "PR"], ["PE", "PE"], ["PI", "PI"], ["RJ", "RJ"], ["RN", "RN"], ["RS", "RS"], ["RO", "RO"], ["RR", "RR"], ["SC", "SC"], ["SP", "SP"], ["SE", "SE"], ["TO", "TO"]]), :class= => "uf dk validate[required]" %> <br /><br />
  
    <%= f.label :zip_code, "CEP"  %><label style="margin-left:195px;">TELEFONE</label><br />
    <%= f.text_field :zip_code , :class =>"a_content1_input_cep validate[required]" %>
    <%= f.text_field :phone , :class=>"a_content1_input_tel validate[required]"%>    
    
    <br />
    <%= f.label :mobile , "Celular" %><br />
    <%= f.text_field :mobile , :class =>"a_content1_input validate[required]" %>
    
  
    <%= f.label :e_mail , "EMAIL"  %><br />
    <%= f.text_field :e_mail , :class =>"a_content1_input validate[required] validate[required,custom[email]]" %>
    
  
    <%= f.label :category, "CATEGORIA", :class =>"categoria dk validate[required]" %> 
    <%= f.select :category, ([["teste1", "teste1"], ["teste2", "teste2"], ["teste3", "teste3"]]) %> <br /><br />
  
    <br /><br /><br /><br /><br /><br /><br />
    <%= image_tag("tit_sua_empresa.png") %><br />
    <%= f.label :business , "NOME DA EMPRESA" %><br />
    <%= f.text_field :business , :class =>"a_content1_input validate[required]" %>
  
    <%= f.label :area_of_​​expertise, "ÀREA DE ESPECIALIDADE", :class =>"categoria dk validate[required]" %> 
    <%= f.select :area_of_​​expertise, ([["teste1", "teste1"], ["teste2", "teste2"], ["teste3", "teste3"]]) %> <br /><br />
  
    <%= f.label :business_phone, "TELEFONE"  %><br />
    <%= f.text_field :business_phone , :class =>"a_content1_input validate[required]" %>
  
    <%= f.label :availability, "DISPONIBILIDADE", :class =>"categoria dk validate[required]" %> 
    <%= f.select :availability, ([["teste1", "teste1"], ["teste2", "teste2"], ["teste3", "teste3"]]) %> <br /><br />  

    <%= f.label :performance_field, "ÀREA DE ATUAÇÃO", :class =>"categoria dk validate[required]" %> 
    <%= f.select :performance_field, ([["teste1", "teste1"], ["teste2", "teste2"], ["teste3", "teste3"]]) %> <br /><br />  
  <%= image_submit_tag("bt_cadastrar.png", :style =>"float:right;")%>
<% end %>

app/views/providers/edit.html.erb
<% title "Edit Provider" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @provider %> |
  <%= link_to "View All", providers_path %>
</p>

app/views/providers/index.html.erb
<% title "Providers" %>

<table>
  <tr>
    <th>Name</th>
    <th>Last Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip Code</th>
    <th>Number</th>
    <th>Phone</th>
    <th>Mobile</th>
    <th>E-Mail</th>
    <th>Category</th>
    <th>Business</th>
    <th>Area Of ​​expertise</th>
    <th>Business Phone</th>
    <th>Availability</th>
    <th>Performance Field</th>
  </tr>
  <% for provider in @providers %>
    <tr>
      <td><%= provider.name %></td>
      <td><%= provider.last_name %></td>
      <td><%= provider.address %></td>
      <td><%= provider.city %></td>
      <td><%= provider.state %></td>
      <td><%= provider.zip_code %></td>
      <td><%= provider.number %></td>
      <td><%= provider.phone %></td>
      <td><%= provider.mobile %></td>
      <td><%= provider.e_mail %></td>
      <td><%= provider.category %></td>
      <td><%= provider.business %></td>
      <td><%= provider.area_of_​​expertise %></td>
      <td><%= provider.business_phone %></td>
      <td><%= provider.availability %></td>
      <td><%= provider.performance_field %></td>
      <td><%= link_to "Show", provider %></td>
      <td><%= link_to "Edit", edit_provider_path(provider) %></td>
      <td><%= link_to "Destroy", provider, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Provider", new_provider_path %></p>

app/views/providers/new.html.erb
<% title "New Provider" %>
<%content_for :head do%>
	<%= stylesheet_link_tag "cadastro.css"%>
<%end%>

    <div id='article'>
    	<div id='a_text'>
        	<%= image_tag("tit_mostrese.png") %>
            <p>Esta área foi criada para que você pudesse ser encontrado com mais rapidez e facilidade por contratantes que buscam seu perfil de profissional. Para se cadastrar, preencha os campos abaixo.</p>
        </div>
        <div id="a_content1">

        <%= image_tag("tit_sobre_voce.png") %>
        <%= render 'form' %>
        
        </div>
    </div>

app/views/providers/show.html.erb
<% title "Provider" %>
<%content_for :head do%>
	<%= stylesheet_link_tag "cadastro.css"%>
<%end%>
    <div id='article'>

    	<div id='a_content1' style="width: 570px !important; margin-top: 50px !important; color:#fff !important;">
        	<h2>Parabéns!</h2>
        	<p class="a_text1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis pharetra odio. Nam a purus orci. Sed sit amet dapibus est. Vestibulum vel commodo turpis. Nunc ligula quam, malesuada sit amet ornare sit amet, aliquam a lorem. Aliquam non elit in ante viverra eleifend.</p>
        </div>
        
    </div>
<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @provider.last_name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @provider.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @provider.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @provider.state %>
</p>
<p>
  <strong>Zip Code:</strong>
  <%= @provider.zip_code %>
</p>
<p>
  <strong>Number:</strong>
  <%= @provider.number %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @provider.phone %>
</p>
<p>
  <strong>Mobile:</strong>
  <%= @provider.mobile %>
</p>
<p>
  <strong>E-Mail:</strong>
  <%= @provider.e_mail %>
</p>
<p>
  <strong>Category:</strong>
  <%= @provider.category %>
</p>
<p>
  <strong>Business:</strong>
  <%= @provider.business %>
</p>
<p>
  <strong>Area Of ​​expertise:</strong>
  <%= @provider.area_of_​​expertise %>
</p>
<p>
  <strong>Business Phone:</strong>
  <%= @provider.business_phone %>
</p>
<p>
  <strong>Availability:</strong>
  <%= @provider.availability %>
</p>
<p>
  <strong>Performance Field:</strong>
  <%= @provider.performance_field %>
</p>

<p>
  <%= link_to "Edit", edit_provider_path(@provider) %> |
  <%= link_to "Destroy", @provider, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", providers_path %>
</p>