config/routes.rb
KwEcoMeencontra::Application.routes.draw do

  resources :contacts do 
    member do
        get 'new_id'
    end
  end
  get "privacy_policy/index"

  get "terms_of_user/index"

  get "howitwork/index"
  resources :providers

  get "home/index"

  resources :search do
    collection do
        post 'results'
    end
  end
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  namespace(:admin){
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #attr_accessible :name, :e_mail, :message, :provider_id
  belongs_to :provider
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  #attr_accessible :name, :last_name, :address, :city, :state, :zip_code, :number, :phone, :mobile, :e_mail, :category, :business, :area_of_​​expertise, :business_phone, :availability, :performance_field
  has_many :contacts 
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout "home"
  def index
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 layout "internal"
  def index
  
  end
  
  def new
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    #@Estados = Reseller.all(:conditions => "active =  true", :group => "state", :order => "state ASC")
    
  end
  
  def results
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    
    #Parameters: {"search"=>{"atuacao"=>"teste2", "categoria"=>"sp", "disponibilidade"=>"teste2"}, "utf8"=>"✓", "y"=>"26", "x"=>"62", "cidade"=>""}
    
    @Resultados = Provider.all(:conditions => ['area_of_​​expertise = ? AND state = ? AND availability = ?', params[:search][:atuacao],params[:search][:estado], params[:search][:disponibilidade]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if !@user.update_attributes(params[:user])
      @user.errors
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/howitwork_helper.rb
module HowitworkHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/privacy_policy_helper.rb
module PrivacyPolicyHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/serach_helper.rb
module SerachHelper
end

app/helpers/terms_of_user_helper.rb
module TermsOfUserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>estetteteestetteteestettete</p>t

app/views/search/new.html.erb
<%content_for :head do%>
	<%= stylesheet_link_tag "pesquisa.css" %>
<%end%>

    <div id='article'>
    	<div id='a_text'>
        	<%= image_tag("tit_encontre.png")%>
            <p>Selecione no formulário abaixo as opções que correspondem com o perfil do profissional que você procura.</p>
        </div>
    	<div id='a_content1'>
        	
            <%=form_tag results_search_index_path, :method => :post%>     
                      
                <%= collection_select :search, :cidade, @Cidades, :city, :city,{:prompt => "CIDADE", :size=>"10"}, :class => "categoria dk" %> 
                <%= collection_select :search, :estado, @Estados, :state, :state,{:prompt => "ESTADO", :size=>"10"}, :class => "categoria dk" %>                
                <%= collection_select :search, :atuacao, @Atuacao, :area_of_​​expertise, :area_of_​​expertise,{:prompt => "AREA DE ATUAÇÃO", :size=>"10"}, :class => "area dk" %>                
                <%= collection_select :search, :disponibilidade, @Disponibilidade, :availability, :availability,{:prompt => "DISPONIBILIDADE", :size=>"10"}, :class => "disponibilidade dk" %>
                <%=image_submit_tag("bt_pesquisar.png", :style => "float:right;")%>
            </form>
        </div>
        <div id='a_content2'>
        	<%= image_tag("tit_resultados.png")%>
                <!-- <div id="box_resultado">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br />
    In convallis magna eget augue luctus sit amet feugiat ipsum euismod. Fusce euismod, turpis ut bibendum rhoncus, libero mauris dapibus est, quis elementum nisi diam non arcu.<br />Curabitur congue dictum turpis, vel tincidunt enim adipiscing vel. Sed pulvinar aliquam risus, vitae aliquet mauris convallis vel. <br />
                    <%#= link_to image_tag("bt_contato.png", :class =>"bt_contato fancybox"), "pesquisalightbox.html", new_contact_path%>
                </p>
                </div> -->
                <div class="clear"></div>
            </div>
        </div>
    

app/views/search/results.html.erb
<%content_for :head do%>
	<%= stylesheet_link_tag "pesquisa.css" %>
<%end%>

    <div id='article'>
    	<div id='a_text'>
        	<%= image_tag("tit_encontre.png")%>
            <p>Selecione no formulário abaixo as opções que correspondem com o perfil do profissional que você procura.</p>
        </div>
    	<div id='a_content1'>        	
            <%=form_tag results_search_index_path, :method => :post%>               
                <%= collection_select :search, :cidade, @Cidades, :city, :city,{:prompt => "CIDADE", :size=>"10"}, :class => "categoria dk" %>                
                <%= collection_select :search, :estado, @Estados, :state, :state,{:prompt => "ESTADO", :size=>"10"}, :class => "categoria dk" %>              
                <%= collection_select :search, :atuacao, @Atuacao, :area_of_​​expertise, :area_of_​​expertise,{:prompt => "AREA DE ATUAÇÃO", :size=>"10"}, :class => "area dk" %>                
                <%= collection_select :search, :disponibilidade, @Disponibilidade, :availability, :availability,{:prompt => "DISPONIBILIDADE", :size=>"10"}, :class => "disponibilidade dk" %>
                <%=image_submit_tag("bt_pesquisar.png", :style => "float:right;")%>
            </form>
        </div>
        <div id='a_content2'>
        	<%= image_tag("tit_resultados.png")%>
                
                <%@Resultados.each do |r|%>
                    <div id="box_resultado">
                        <br />
                        <p><b>Nome:</b> <%=r.name%><br />
                        <p><b>Cidade:</b> <%=r.city%><br />
                        <p><b>Estado:</b> <%=r.state%><br />
                        <p><b>Area de atuação:</b> <%=r.area_of_​​expertise%><br />
                        <%= link_to image_tag("bt_contato.png", :class =>"bt_contato"), new_id_contact_path(r), :class => "fancybox" %>
                        </p>
                    </div>
                <%end%>
                <div class="clear"></div>
            </div>
        </div>
    