config/routes.rb
KwEcoMeencontra::Application.routes.draw do

  resources :contacts do 
    member do
        get 'new_id'
    end
  end
  get "privacy_policy/index"

  get "terms_of_user/index"

  get "howitwork/index"
  resources :providers

  get "home/index"

  resources :search do
    collection do
        post 'results'
    end
  end
  resources :user_sessions
  resources :users
  resources :password_resets
  resources :atualizar
  namespace(:admin){
    resources :static_contents
    resources :users do
      collection do
        get 'search'
      end
    end
    
    root :to => "static_contents#index"
  }
  
  root :to => "home#index"
  match 'cadastro' => "users#new"
  match 'login' => 'user_sessions#new'  
  match 'logout' => 'user_sessions#destroy'  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  #attr_accessible :name, :e_mail, :message, :provider_id
  belongs_to :provider
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  #attr_accessible :name, :last_name, :address, :city, :state, :zip_code, :number, :phone, :mobile, :e_mail, :category, :business, :area_of_​​expertise, :business_phone, :availability, :performance_field
  has_many :contacts 
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_authorization_role
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
  
  acts_as_authorization_subject
  
  scoped_search :on => [:name, :last_name, :email]
  
  validates_presence_of :name, :message=> " - preencha o campo!"
  validates_presence_of :last_name, :message=> " - preencha o campo!"
  validates_presence_of :email, :message=> " - preencha o campo!"
  
  attr_writer :role
  after_save :define_role

  def role
    @role
    if self.has_role? :admin
      @role = :admin
    elsif self.has_role? :supervisor
      @role = :supervisor
    elsif self.has_role? :user
      @role = :user
    end
  end

  def define_role
    if @role
      self.has_no_roles!
      self.has_role! @role
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout "home"
  def index
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 layout "internal"
  def index
  
  end
  
  def new
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    #@Estados = Reseller.all(:conditions => "active =  true", :group => "state", :order => "state ASC")
    
  end
  
  def results
    @Cidades = Provider.all(:group => "city")
    @Estados = Provider.all(:group => "state")
    @Atuacao = Provider.all(:group => "area_of_​​expertise")
    @Disponibilidade = Provider.all(:group => "availability")
    
    #Parameters: {"search"=>{"atuacao"=>"teste2", "categoria"=>"sp", "disponibilidade"=>"teste2"}, "utf8"=>"✓", "y"=>"26", "x"=>"62", "cidade"=>""}
    
    @Resultados = Provider.all(:conditions => ['area_of_​​expertise = ? AND state = ? AND availability = ?', params[:search][:atuacao],params[:search][:estado], params[:search][:disponibilidade]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :navegadorie6
  layout "admin"
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role = "user"    
    if !@user.save
      @user.errors
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if !@user.update_attributes(params[:user])
      @user.errors
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atualizar_helper.rb
module AtualizarHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/howitwork_helper.rb
module HowitworkHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/serach_helper.rb
module SerachHelper
end

app/helpers/terms_of_user_helper.rb
module TermsOfUserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Administrador Korewa - " + yield(:title) : "Administrador Korewa" %></title>
<%= stylesheet_link_tag "admin"%>
<%= javascript_include_tag :defaults %>
<script>
jQuery.noConflict();
</script>
<%= javascript_include_tag "menuadmin.js" %>
<%=yield :head%>
</head>
<body>
	<div id="General">
		<div id="Header">
			<div id="User_bar">
				<div id="User_bar_content">
					<%if current_user%>
					<div id="User_name">
						<%= link_to image_tag("img_house.png", :width=>"28", :height=>"23", :class=>"Usr_bt_align"), root_path%><span>Bem Vindo, <%= current_user.name %></span>
					</div>
					<div id="Buttons">
						<%= link_to(image_tag("bt_config.png", :width=>"22", :height=>"22") , edit_user_path(:current), :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_ajuda.png", :width=>"22", :height=>"22") , "", :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_logout.png", :width=>"22", :height=>"22") , logout_path, :class => "Usr_bt_align") %>
					</div>
					<%end%>
				</div>
			</div>
			<div id="Logo">
				<%= image_tag("logo_default.png", :width=>"148", :height=>"83")%>
			</div>
		</div>
		<div id="Content">
			<div id="Right_box">
				<%=yield%>
			</div>    
			<div class="clear"></div>
			<div id="Footer">
				<div id="Footer_content">
					<p>Kore.Wa CMS © 2011 - all rights reserved.</p> 
					<ul>
						<li><a href="#">Politica de privacidade&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Termos de Uso&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Ajuda&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Suporte </a></li>
					</ul>
					<br />
					<%= link_to(image_tag("logo_korewa.png",:width=>"130",:height=>"54",:alt=>"korewa",:title=>"korewa",:style=>" display:block; float:right; margin-top:70px;"),'http://www.korewa.com.br/')%>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/atualizar.html.erb
<%= yield %>

app/views/layouts/blank.html.erb
<%= yield :head %>
<%= yield %>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Ecoverde - " + yield(:title) : "Ecoverde" %></title>
<%= stylesheet_link_tag "reset.css"%>
<%= stylesheet_link_tag "home.css"%>
<%= javascript_include_tag "jquery.js" %>
<script>
jQuery.noConflict();
</script>

</head>
<body>
<div id='section'>
	<div id='header'>
    	<div id='h_logo'>
        	<%=link_to image_tag("logo.png"), root_path%>
        </div>
        <div id='h_info'>
        	<%=link_to image_tag("bt_como_funciona.png"), howitwork_index_path%>
        </div>
    </div>
    <div id='article'>
    	<div id='a_text'>
        	<img src="images/tit_seja_bem_vindo.png" border="0"/>
            <p>Preparamos esta ferramenta para que você possa encontrar com rapidez e segurança os profissionais mais indicados para sua obra. Este espaço permite também que você faça seu cadastro para ser encontrado por outros profissionais. Selecione abaixo o que você deseja fazer.</p>
        </div>
    	<div id='a_button1'>
        	<%= link_to image_tag("bt_sou_profissional.png"), new_provider_path %>
        </div>
        <div id='a_button2'>
            <%= link_to image_tag("bt_quero_encontrar.png"), new_search_path %>
        </div>
    </div>
    <div id='footer'>
    	<div id='f_left'>
        	<p>ecoverde © Todos os direitos reservados</p>
        </div>
        <div id='f_right'>
        	<%= link_to "termos", terms_of_user_index_path %>|<%= link_to "política", privacy_policy_index_path %><%= link_to image_tag("bt_facebook.png"), "#" %>
        </div>
    </div>
</div>
</body>
</html>

app/views/layouts/inadmin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Administrador Korewa - " + yield(:title) : "Administrador Korewa" %></title>
<%= stylesheet_link_tag "admin"%>
<%= javascript_include_tag :defaults %>
<script>
jQuery.noConflict();
</script>
<%= javascript_include_tag "menuadmin.js" %>
<%= javascript_include_tag "jquery.tablesorter.min.js" %>
<%=yield :head%>
<script>
jQuery(document).ready(function() 
    { 
	//	jQuery("li:first.parent > a").trigger('click');
        jQuery("table").tablesorter(); 
    } 
);
</script>
</head>
<body>
	<div id="General">
		<div id="Header">
			<div id="User_bar">
				<div id="User_bar_content">
					<div id="User_name">
						<%= link_to image_tag("img_house.png", :width=>"28", :height=>"23", :class=>"Usr_bt_align"), root_path%><span>Bem Vindo, <%= current_user.name %></span>
					</div>
					<div id="Buttons">
						<%= link_to(image_tag("bt_config.png", :width=>"22", :height=>"22") , edit_user_path(:current), :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_ajuda.png", :width=>"22", :height=>"22") , "", :class => "Usr_bt_align") %>
						<%= link_to(image_tag("bt_logout.png", :width=>"22", :height=>"22") , logout_path, :class => "Usr_bt_align") %>
					</div>
				</div>
			</div>
			<div id="Logo">
				<%= image_tag("logo_default.png", :width=>"148", :height=>"83")%>
			</div>
		</div>
		<div id="Content">
			<div id="Left_box">
				<div id="Item_category" >
					<div id="Item_content">
						<ul id="menu">
							<li class="parent aberto"><a href="#" title=""><h3>Empresas</h3></a>
								<ul class="sub-menu">
									<li>Empresa 1</li>
									<li>Empresa 2</li>
									<li>Empresa 3</li>
									<li>Empresa 4</li>
									<li>Empresa 5</li>
								</ul>
							</li>
							<%if User.find(current_user.id).has_role? :admin %>
							<li class="parent aberto"><a href="#" title=""><h3>Ajuste do Site</h3></a>
								<ul class="sub-menu">
									<li><%= link_to "Gerenciar Usuários",admin_users_path%></li>
								</ul>
							</li>
							<%end%>

						</ul>
					</div>
				</div>
			</div>
			<div id="Right_box">
				<%=yield%>
			</div>    
			<div class="clear"></div>
			<div id="Footer">
				<div id="Footer_content">
					<p>Kore.Wa CMS © 2011 - all rights reserved.</p> 
					<ul>
						<li><a href="#">Politica de privacidade&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Termos de Uso&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Ajuda&nbsp;</a>•&nbsp;</li>
						<li><a href="#">Suporte </a></li>
					</ul>
					<br />
					<%= link_to(image_tag("logo_korewa.png",:width=>"130",:height=>"54",:alt=>"korewa",:title=>"korewa",:style=>" display:block; float:right; margin-top:70px;"),'http://www.korewa.com.br/')%>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/internal.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= content_for?(:title) ? "Ecoverde - " + yield(:title) : "Ecoverde" %></title>
<%= stylesheet_link_tag "reset.css"%>
<%= stylesheet_link_tag "dropkick.css"%>
<%= stylesheet_link_tag "../javascripts/fancybox/jquery.fancybox.css"%>
<%= stylesheet_link_tag "validationEngine.jquery.css" %>
<%= javascript_include_tag "jquery.js" %>
<script>
jQuery.noConflict();
</script>
<%= javascript_include_tag "jquery.dropkick-1.0.0.js" %>
<%= javascript_include_tag "scrollability.min.js" %>
<%= javascript_include_tag "fancybox/jquery.fancybox.js" %>
<%= javascript_include_tag "jquery.validationEngine-en.js" %>
<%= javascript_include_tag "jquery.validationEngine.js" %>
<%= yield :head %>

<script>
	jQuery(document).ready(function(e) {
		
		jQuery('.fancybox').fancybox({
		     'type' : 'iframe'
		});

		jQuery('.uf').dropkick();
		jQuery('.categoria').dropkick();
		jQuery('.area').dropkick();
		jQuery('.disponibilidade').dropkick();
		jQuery('.atuacao').dropkick();
    });
	jQuery(document).ready(function(){

			// binds form submission and fields to the validation engine

			jQuery("#formID").validationEngine();

		});
    jQuery('#email1').validationEngine('hide');


		/**

		*

		* @param {jqObject} the field where the validation applies

		* @param {Array[String]} validation rules for this field

		* @param {int} rule index

		* @param {Map} form options

		* @return an error string if validation failed

		*/

		function checkHELLO(field, rules, i, options){

			if (field.val() != "HELLO") {

				// this allows to use i18 for the error msgs

				return options.allrules.validate2fields.alertText;

			}

		}
            
		// This method is called right before the ajax form validation request
		// it is typically used to setup some visuals ("Please wait...");
		// you may return a false to stop the request 
		function beforeCall(form, options){
			if (window.console) 
			console.log("Right before the AJAX form validation call");
			return true;
		}
            
		// Called once the server replies to the ajax form validation request
		function ajaxValidationCallback(status, form, json, options){
			if (window.console) 
			console.log(status);
                
			if (status === true) {
				alert("the form is valid!");
				// uncomment these lines to submit the form to form.action
				// form.validationEngine('detach');
				// form.submit();
				// or you may use AJAX again to submit the data
			}
		}
            
		jQuery(document).ready(function(){
			jQuery("#formID").validationEngine({
				ajaxFormValidation: true,
				onAjaxFormComplete: ajaxValidationCallback,
			});
		});
  </script>
</head>
<body>
<div id='section'>
	<div id='header'>
    	<div id='h_logo'>
        	<%= link_to image_tag("logo.png"), root_path %>
        </div>
        <div id='h_info'>
        	<%= link_to image_tag("bt_como_funciona.png"), root_path %>
        </div>
    </div>
    <%= yield %>
    
    <div id='footer'>
        
    	<div id='f_left'>
        	<p>ecoverde © Todos os direitos reservados</p>
        </div>
        <div id='f_right'>
        	<%= link_to "termos", terms_of_user_index_path %>|<%= link_to "política", privacy_policy_index_path %><%= link_to image_tag("bt_facebook.png"), "#" %>
    </div>
    
</div>
</div>
</body>
</html>